### ISSUE TITLE
R key

### ISSUE THREAD

**Issue by silverfish8** [fallenswordhelper/fallenswordhelper#182]
It used to be when the R key was pressed, it repaired your gear AND THEN took you to the map screen.  Now when you press the R key, it takes you to the blasksmith screen.  This is kind of a waste b/c once you hit R all things are repaired.  You don't need to be on the blacksmith screen. Can you put it back the old way where when you hit R it takes you to the map screen? thanks.

**Comment by atompkins** [comment]
This was old map functionality and still works on the old map.
The problem with what FSH was doing is that your items are repaired only if you have enough gold. On the old map it tells you if you don't have enough gold. The new map doesn't.
In order to simulate this properly for the new map we will need a new UrlParameter for the world which we can detect and invoke repair. If you don't have enough gold you would then get the normal message.

**Comment by atompkins** [comment]
i'm just gonna YOLO it and see if anyone complains
