### ISSUE TITLE
 "move selected items to" on manage backpack ("b") broken

### ISSUE THREAD

**Issue by Rover2** [fallenswordhelper/fallenswordhelper#66]
...whatever is selected, nothing is moved to the specified backpack folder if you press the "move" button.
I first experienced this behaviour nearly a year ago, so it has nothing to do with recent changes.
Tested on: Win7Pro 64bit, FF 31.2.0 ESR and FF 38.2.1 ESR, Greasemonkey 1.15 and 2.0 and 3.4.1 (other Add-ons: only ReloadEvery 28.0.2.1-signed).

**Comment by atompkins** [comment]
This may be related to FF ESR. I am unable to reproduce on standard version.
Need to setup test environment.
Question: Should we be supporting ESR?

**Comment by yuuzhan** [comment]
I noticed this a while ago - it had to do with the page reloading before the javascript had a chance to run - thus technically cancelling the move.  You can simulate a slow internet connection by adding a sleep command or something.  I see this on a fast connection when selecting a LOT of items (thus multiple groups of 16 needing to be called)

Since our (your) time is limited, my gut feeling is no - but the issue might not be related to ESR

Replicated on (Current version: 1508b2) on chrome (user agent Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.93 Safari/537.36)

**Comment by atompkins** [comment]
OK that's interesting. I just got it to refresh the page before the move was complete so it looked as if it hadn't done it...

**Comment by yuuzhan** [comment]
Just so it is here:

yuuzhan [1:38 PM]
line 4987

yuuzhan [1:38 PM]
$.ajax({
                    type: 'POST',
                    url: System.server + 'index.php',
                    data: postData + postItems
                });

pointyhair [1:38 PM] 
well i've been looked for an excuse to play with wanemu

yuuzhan [1:38 PM] 
is not executing before thid

yuuzhan [1:38 PM]
if (haveItems) {
            setTimeout(function() {location.reload();}, 100);
        }

yuuzhan [1:39 PM]
so some of the moves dont go out

pointyhair [1:39 PM] 
ah yes the delightful random timeouts...
